### ISSUE TITLE
"Failed to convert file to pdf"

### ISSUE THREAD

**Issue by MartijnGP** [simoncadman/CUPS-Cloud-Print#98]
Hi!

I'm running into some issues. I managed to add my cloud printer (Canon MG2950, has its own connection to cloud print, using gutenprint drivers on Linux Mint 17.3 x64) to CUPS but it won't accept any prints, saying "Failed to convert file to pdf". It won't be any more specific than that. CUPS' error_log holds nothing, cloudprint_log says the same thing about the failure without providing more information. By modifying /usr/lib/cups/backend/gcp to dump p.__dict__ after sending stuff to ps2pdf, I did notice that it returns with code 1, but I have not been able to debug that any further. Removing the check for the returncode, making it continue anyway, yields "Job data is empty" as an error.

Do you know of a solution, or a way to get more details from it?

Regards,
MartijnGP

**Comment by simoncadman** [comment]
I've released a new version of CUPS Cloud Print ( 20160502 ), can you see if it now works with this new version.

Thanks

**Comment by netllama** [comment]
I'm using the latest version of CUPS Cloud Print, and I can still reproduce this same error.

**Comment by netllama** [comment]
This is what I see in cloudprint_log when it fails:
```
2016-11-18 07:28:44|INFO|Printing file A9ROxC0jwM
2016-11-18 07:28:44|INFO|Device is gcp://lfriedman%40netflix.com/6428d622-538e-95a4-5d2a-12d51d6de4a2 , printername is gcp-lg-d1-Gabbeh, params
 are: '/usr/lib/cups/backend/gcp' '815' 'netllama' 'A9ROxC0jwM' '1' 'color=STANDARD_COLOR duplex=NO_DUPLEX finishings=3 fit_to_page=FIT_TO_PAGE
 media=oe_letter-fullbleed_8.5x11in media_size=Letter number-up=1 output-bin=face-down page_orientation=PORTRAIT PageRegion=Letter.Fullbleed Pa
geSize=Letter.Fullbleed print-color-mode=color print-quality=4 job-uuid=urn:uuid:a6562929-06c5-3c69-796e-b36108c914d5 job-originating-host-name
=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1479482923 time-at-processing=1479482923 document-name-supplied=A9R
OxC0jwM'
2016-11-18 07:28:44|ERROR|Using these params /usr/bin/ps2pdf -dPDFSETTINGS=/printer -dUseCIEColor - -
2016-11-18 07:28:44|ERROR|Error from converting file to pdf: GPL Ghostscript 9.20: 

Use of -dUseCIEColor detected!
Since the release of version 9.11 of Ghostscript we recommend you do not set
-dUseCIEColor with the pdfwrite/ps2write device family.

This PostScript file was created from an encrypted PDF file.
Redistilling encrypted PDF is not permitted.
Error: /undefined in --eexec--
Operand stack:
   --nostringval--   --dict:95/200(L)--   quit
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1999   1   3   %oparray_pop   1998   1   3   %oparray_pop   1982   1   3   %oparray_pop   1868   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   1859   2   3   %oparray_pop   --nostringval--   --nostringval--   --nostringval--
Dictionary stack:
   --dict:1209/1684(ro)(G)--   --dict:1/20(G)--   --dict:95/200(L)--   --dict:1209/1684(ro)(G)--
Current allocation mode is local
Last OS error: Not a directory
GPL Ghostscript 9.20: Unrecoverable error, exit code 1
```

**Comment by netllama** [comment]
After further investigation, the problem is that the PDFs that are failing to work are 'Secured' PDFs, which cannot have pages 'extracted' from them.  If I manually re-generate the Secured PDFs from the original, such that they are no longer secured, then I can print the newly generated PDF just fine using CUPS-Cloud-Print.  This is the command that I used to regenerate the original (3855992.pdf) secured PDF into an unsecured PDF:
`gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dSAFER -dFirstPage=1 -dLastPage=3 -sOutputFile=0.pdf 3855992.pdf`

This definitely looks like a bug in CUPS-Cloud-Print, as it should be able to figure this out on its own, and do the right thing.
